# Generated by Django 4.0.4 on 2024-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('known_skills', models.TextField(blank=True)),
                ('courses', models.ManyToManyField(related_name='teachers', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
