# Generated by Django 4.0.4 on 2024-08-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.assignment')),
            ],
            options={
                'unique_together': {('assignment', 'question_index')},
            },
        ),
    ]
