# Generated by Django 4.0.4 on 2024-08-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assignmentprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentProgress',
        ),
    ]
