# Generated by Django 4.0.4 on 2024-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_delete_assignmentprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_answer',
            field=models.TextField(blank=True),
        ),
    ]
