# Generated by Django 4.0.4 on 2024-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_sentence_userprogress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='text',
            new_name='sentence',
        ),
        migrations.AddField(
            model_name='sentence',
            name='assignment_id',
            field=models.PositiveIntegerField(default=121),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='correct_sentence',
            field=models.CharField(default=121, max_length=255),
            preserve_default=False,
        ),
    ]
