# Generated by Django 4.0.4 on 2024-08-21 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_rename_text_sentence_sentence_sentence_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sentences', to=settings.AUTH_USER_MODEL),
        ),
    ]
