# Generated by Django 4.0.4 on 2024-08-22 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_sentence_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_sentence', models.CharField(max_length=255)),
                ('sentence', models.CharField(max_length=255)),
                ('assignment_id', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='course.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sentences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='sentences',
            field=models.ManyToManyField(related_name='user_progress_sentences', to='course.sentences'),
        ),
    ]
