# Generated by Django 4.0.4 on 2024-08-22 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_sentences_delete_sentence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentences',
            new_name='Sentence',
        ),
    ]
